/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.7
 * Generated at: 2018-07-04 15:36:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Model.*;
import Dao.*;
import Interface.*;
import java.util.List;
import java.util.ArrayList;

public final class Index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("Dao");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("Model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("Interface");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Home</title>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/icons.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"css/materialize.css\" type=\"text/css\" rel=\"stylesheet\"\r\n");
      out.write("\tmedia=\"screen,projection\" />\r\n");
      out.write("<link href=\"css/style.css\" type=\"text/css\" rel=\"stylesheet\"\r\n");
      out.write("\tmedia=\"screen,projection\" />\r\n");
      out.write("<link href=\"css/style2.css\" type=\"text/css\" rel=\"stylesheet\"\r\n");
      out.write("\tmedia=\"screen,projection\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"Menu\">\r\n");
      out.write("\t\t<nav>\r\n");
      out.write("\t\t\t<div class=\"nav-wrapper\" style=\"background-color: teal;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"brand-logo left\">APS5 CC</a> <a href=\"#\"\r\n");
      out.write("\t\t\t\t\tdata-target=\"menu-mobile\" class=\"sidenav-trigger right\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"material-icons\">menu</i></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<ul id=\"nav-mobile\" class=\"right hide-on-med-and-down\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Index.jsp\" class=\"z-depth-3\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Ocorrencias.jsp\">Ocorrências</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Relatorios.jsp\">Relatórios</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Cadastrar.jsp\">Cadastrar</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"QuemSomos.jsp\">Quem somos</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<ul id=\"menu-mobile\" class=\"sidenav\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Index.jsp\" class=\"z-depth-3\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Ocorrencias.jsp\">Ocorrências</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Relatorios.jsp\">Relatórios</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Cadastrar.jsp\">Cadastrar</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"QuemSomos.jsp\">Quem somos</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"parallax-container valign-wrapper\">\r\n");
      out.write("\t\t<div class=\"section no-pad-bot\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row center\">\r\n");
      out.write("\t\t\t\t\t<h5 class=\"header col s12 light\" style=\"font-size: 45px\">Controle\r\n");
      out.write("\t\t\t\t\t\tde atividades industriais no Rio Tietê</h5>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"parallax\">\r\n");
      out.write("\t\t\t<img src=\"img\\tiete01.jpg\" alt=\"Unsplashed background img 2\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<ul class=\"listaNav\"\r\n");
      out.write("\t\tstyle=\"text-align: center; margin-left: 10%; margin-right: 10%\">\r\n");
      out.write("\t\t<li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<canvas id=\"myChart1\" width=\"300\" height=\"300\"></canvas> <script\r\n");
      out.write("\t\t\t\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js\"></script>\r\n");
      out.write("\t\t\t<script>\r\n");
      out.write("                    var ctx = document.getElementById(\"myChart1\");\r\n");
      out.write("                    var myChart = new Chart(ctx, {\r\n");
      out.write("                        type: 'doughnut',\r\n");
      out.write("                        data: {\r\n");
      out.write("                        \t");

                        	Ificha graf1 = new FichaDAO();
                        	Relatorio rel1 = graf1.OxE();
                        	String label1 = rel1.getId();
                        	
                        	
      out.write("\r\n");
      out.write("                        labels: [");
      out.print(label1);
      out.write("],\r\n");
      out.write("                        datasets: [{\r\n");
      out.write("                        label: '# of Votes',\r\n");
      out.write("                        ");
String date1 = rel1.getNumeros();
      out.write("\r\n");
      out.write("                        data: [");
      out.print(date1);
      out.write("],\r\n");
      out.write("                        backgroundColor: [\r\n");
      out.write("                            'rgba(255, 99, 132, 0.2)',\r\n");
      out.write("                            'rgba(54, 162, 235, 0.2)',\r\n");
      out.write("                            'rgba(255, 206, 86, 0.2)',\r\n");
      out.write("                            'rgba(75, 192, 192, 0.2)',\r\n");
      out.write("                            'rgba(153, 102, 255, 0.2)',\r\n");
      out.write("                            'rgba(255, 159, 64, 0.2)'\r\n");
      out.write("                        ],\r\n");
      out.write("                        borderColor: [\r\n");
      out.write("                            'rgba(255,99,132,1)',\r\n");
      out.write("                            'rgba(54, 162, 235, 1)',    \r\n");
      out.write("                            'rgba(255, 206, 86, 1)',\r\n");
      out.write("                            'rgba(75, 192, 192, 1)',\r\n");
      out.write("                            'rgba(153, 102, 255, 1)',\r\n");
      out.write("                            'rgba(255, 159, 64, 1)'\r\n");
      out.write("                        ],\r\n");
      out.write("                        borderWidth: 1\r\n");
      out.write("                        }]\r\n");
      out.write("                        },\r\n");
      out.write("                        options: {\r\n");
      out.write("                            title: {\r\n");
      out.write("                                display: true,\r\n");
      out.write("                                text: 'Poluição por Empresa'\r\n");
      out.write("                            },\r\n");
      out.write("                            scales: {\r\n");
      out.write("                                yAxes: [{\r\n");
      out.write("                                    ticks: {\r\n");
      out.write("                                        beginAtZero:true\r\n");
      out.write("                                    }\r\n");
      out.write("                                }]\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                    });\r\n");
      out.write("                </script>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<canvas id=\"myChart2\" width=\"300\" height=\"300\"></canvas> <script\r\n");
      out.write("\t\t\t\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js\"></script>\r\n");
      out.write("\t\t\t<script>\r\n");
      out.write("                    var ctx = document.getElementById(\"myChart2\");\r\n");
      out.write("                    var myChart = new Chart(ctx, {\r\n");
      out.write("                        type: 'doughnut',\r\n");
      out.write("                        data: {\r\n");
      out.write("                        \t");

                        	Ificha graf2 = new FichaDAO();
                        	Relatorio rel2 = graf2.PxC();
                        	String label2 = rel2.getId();
                        	
                        	
      out.write("\r\n");
      out.write("                        labels: [");
      out.print(label2);
      out.write("],\r\n");
      out.write("                        datasets: [{\r\n");
      out.write("                        label: '# of Votes',\r\n");
      out.write("                        ");
String date2 = rel2.getNumeros();
      out.write("\r\n");
      out.write("                        data: [");
      out.print(date2);
      out.write("],\r\n");
      out.write("                        backgroundColor: [\r\n");
      out.write("                            'rgba(255, 99, 132, 0.2)',\r\n");
      out.write("                            'rgba(54, 162, 235, 0.2)',\r\n");
      out.write("                            'rgba(255, 206, 86, 0.2)',\r\n");
      out.write("                            'rgba(75, 192, 192, 0.2)',\r\n");
      out.write("                            'rgba(153, 102, 255, 0.2)',\r\n");
      out.write("                            'rgba(255, 159, 64, 0.2)'\r\n");
      out.write("                        ],\r\n");
      out.write("                        borderColor: [\r\n");
      out.write("                            'rgba(255,99,132,1)',\r\n");
      out.write("                            'rgba(54, 162, 235, 1)',    \r\n");
      out.write("                            'rgba(255, 206, 86, 1)',\r\n");
      out.write("                            'rgba(75, 192, 192, 1)',\r\n");
      out.write("                            'rgba(153, 102, 255, 1)',\r\n");
      out.write("                            'rgba(255, 159, 64, 1)'\r\n");
      out.write("                        ],\r\n");
      out.write("                        borderWidth: 1\r\n");
      out.write("                        }]\r\n");
      out.write("                        },\r\n");
      out.write("                        options: {\r\n");
      out.write("                            title: {\r\n");
      out.write("                                display: true,\r\n");
      out.write("                                text: 'Poluição por Cidade'\r\n");
      out.write("                            },\r\n");
      out.write("                            scales: {\r\n");
      out.write("                                yAxes: [{\r\n");
      out.write("                                    ticks: {\r\n");
      out.write("                                        beginAtZero:true\r\n");
      out.write("                                    }\r\n");
      out.write("                                }]\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                    });\r\n");
      out.write("                </script>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<canvas id=\"myChart3\" width=\"300\" height=\"300\"></canvas> <script\r\n");
      out.write("\t\t\t\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js\"></script>\r\n");
      out.write("\t\t\t<script>\r\n");
      out.write("                    var ctx = document.getElementById(\"myChart3\");\r\n");
      out.write("                    var myChart = new Chart(ctx, {\r\n");
      out.write("                        type: 'doughnut',\r\n");
      out.write("                        data: {\r\n");
      out.write("                        \t");

                        	Ificha graf3 = new FichaDAO();
                        	Relatorio rel3 = graf3.AxC();
                        	String label3 = rel3.getId();
                        	
                        	
      out.write("\r\n");
      out.write("                        labels: [");
      out.print(label3);
      out.write("],\r\n");
      out.write("                        datasets: [{\r\n");
      out.write("                        label: '# of Votes',\r\n");
      out.write("                        ");
String date3 = rel3.getNumeros();
      out.write("\r\n");
      out.write("                        data: [");
      out.print(date3);
      out.write("],\r\n");
      out.write("                        backgroundColor: [\r\n");
      out.write("                            'rgba(255, 99, 132, 0.2)',\r\n");
      out.write("                            'rgba(54, 162, 235, 0.2)',\r\n");
      out.write("                            'rgba(255, 206, 86, 0.2)',\r\n");
      out.write("                            'rgba(75, 192, 192, 0.2)',\r\n");
      out.write("                            'rgba(153, 102, 255, 0.2)',\r\n");
      out.write("                            'rgba(255, 159, 64, 0.2)'\r\n");
      out.write("                        ],\r\n");
      out.write("                        borderColor: [\r\n");
      out.write("                            'rgba(255,99,132,1)',\r\n");
      out.write("                            'rgba(54, 162, 235, 1)',    \r\n");
      out.write("                            'rgba(255, 206, 86, 1)',\r\n");
      out.write("                            'rgba(75, 192, 192, 1)',\r\n");
      out.write("                            'rgba(153, 102, 255, 1)',\r\n");
      out.write("                            'rgba(255, 159, 64, 1)'\r\n");
      out.write("                        ],\r\n");
      out.write("                        borderWidth: 1\r\n");
      out.write("                        }]\r\n");
      out.write("                        },\r\n");
      out.write("                        options: {\r\n");
      out.write("                            title: {\r\n");
      out.write("                                display: true,\r\n");
      out.write("                                text: 'Atividades mais Praticadas'\r\n");
      out.write("                            },\r\n");
      out.write("                            scales: {\r\n");
      out.write("                                yAxes: [{\r\n");
      out.write("                                    ticks: {\r\n");
      out.write("                                        beginAtZero:true\r\n");
      out.write("                                    }\r\n");
      out.write("                                }]\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                    });\r\n");
      out.write("                </script>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("</div>\r\n");
      out.write("\t<div style=\"text-align: right; margin-top: 2%; margin-right: 10%\">\r\n");
      out.write("\t\t<a href=\"Relatorios.jsp\">Ver mais...</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div style=\"padding: 10%; padding-top: 2%; padding-bottom: 2%\">\r\n");
      out.write("\t\t<table class=\"highlight\">\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>ID</th>\r\n");
      out.write("\t\t\t\t\t<th>Empresa</th>\r\n");
      out.write("\t\t\t\t\t<th>Atividade</th>\r\n");
      out.write("\t\t\t\t\t<th>Cidade</th>\r\n");
      out.write("\t\t\t\t\t<th>Grupo</th>\r\n");
      out.write("\t\t\t\t\t<th>Agente</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t");

					Iequipe eqp = new EquipeDAO();
					Iatividade atd = new AtividadeDAO();
					Ificha fic = new FichaDAO();
					Iindustria ind = new IndustriaDAO();
					Iagente agt = new AgenteDAO();
					Ilocalizacao cid = new LocalizacaoDAO();
					List<Ficha> lista = fic.selectNConfirmados();
					if (lista != null) {
						for (Ficha ob : lista) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(ob.getIdFicha());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(ind.selectIndustria(ob.getIdIndustria()).getNomeIndustria());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(atd.selectAtividade(ob.getIdAtividade()).getDescricao());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(cid.selectLocalizacao(ind.selectIndustria(ob.getIdIndustria()).getLocalizacao()).getNomeCidade());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(eqp.selectEquipe(agt.selectAgente(ob.getIdAgente()).getIdEquipe()).getNomeEquipe());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(agt.selectAgente(ob.getIdAgente()).getNome());
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");

					}
					}
				
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div style=\"text-align: right; margin-bottom: 2%; margin-right: 10%\">\r\n");
      out.write("\t\t<a href=\"Ocorrencias.jsp\">Ver mais...</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<footer class=\"page-footer\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col l6 s12\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col l4 offset-l2 s12\">\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"white-text\">Links</h5>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"grey-text text-lighten-3\" href=\"Index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"grey-text text-lighten-3\"\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"Ocorrencias.jsp\">Ocorrências</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"grey-text text-lighten-3\"\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"Relatorios.jsp\">Relatórios</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"grey-text text-lighten-3\" href=\"Cadastrar.jsp\">Cadastrar</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"grey-text text-lighten-3\" href=\"QuemSomos.jsp\">Quem\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsomos</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"footer-copyright\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">© 2018 APS - Ciências da Computação -\r\n");
      out.write("\t\t\t\t\t4º e 5º Semestre</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("       \r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/materialize.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/init.js\"></script>\r\n");
      out.write("\t<script>$('.sidenav').sidenav();</script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\r\n");
      out.write("    var ws = new WebSocket(\"ws://10.1.48.134:8000/events/\");\r\n");
      out.write("    ws.onmessage = function(e) {\r\n");
      out.write("    \t//window.location.reload();\r\n");
      out.write("        M.toast({html: 'Existem novas ocorrências a serem confirmadas!'});\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\t\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
